version: '3.4'

services:
  app:
    image: ghcr.io/fmdelgado/drugrepochatter:main
    container_name: drugrepochat
    build: .
    env_file:
      - .env
    ports:
      - "${port_mapping}"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: always
    depends_on:
      - db
    networks:
      - drugrepochatter_net
    volumes:
      - ./app/indexes:/app/app/indexes
      - ./app:/app/app

  db:
    container_name: drugrepochatdb
    image: mysql:8.0
    networks:
      - drugrepochatter_net
    volumes:
      - drugrepochatterdb_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${root_pw}"
      MYSQL_DATABASE: "${db_name}"
    command: --default-authentication-plugin=mysql_native_password

volumes:
  index_volume:
    driver: local
  drugrepochatterdb_volume:
networks:
  drugrepochatter_net: