version: '3.4'

services:
  app:
    image: ghcr.io/fmdelgado/drugrepochatter:main
    container_name: drugrepochat
    build: .
    env_file:
      - .env
    ports:
      - "${port_mapping}"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: always
    depends_on:
      - db
    networks:
      - drugrepochatter_net
    volumes:
      - ./app/indexes:/app/app/indexes  # Synchronize with the 'indexes' directory in your repo
      - ./app:/app/app  # Ensure the current directory is correctly mounted

  db:
    container_name: drugrepochatdb
    platform: linux/x86_64  # Specify platform for emulation
    image: mysql:5.7
    networks:
      - drugrepochatter_net
    volumes:
      - drugrepochatterdb_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${root_pw}"

volumes:
  index_volume:
    driver: local
  drugrepochatterdb_volume:
networks:
  drugrepochatter_net:
